sudo: false

notifications:
  email: false

language: go

go:
  - 1.4
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.5
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.6

services:
  - mongodb
  - mysql
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell

env: GOARCH=amd64 DB_HOST=127.0.0.1 DB_USER=user DB_PASSWORD=pass DB_NAME=testdb

install:
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/db.v2
  - cd $GOPATH/src/upper.io/db.v2
  - go get -t -v -d ./...
  - go get -v github.com/cznic/ql/ql
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/db.v2

before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

script:
  - make test
