sudo: false

language: go

go:
  - 1.3
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4
  - 1.4.1
  - 1.4.2
  - 1.5
  - 1.5.1

install:
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/db.v2/sqlbuilder
  - cd $GOPATH/src/upper.io/db.v2/sqlbuilder
  - go get -v -d -t ./...

script:
  - cd $GOPATH/src/upper.io/db.v2/sqlbuilder
  - make test
